name: Deploy Functions

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{secrets.PROD_ACCESS_TOKEN}}
      SUPABASE_PROJECT_ID: ${{secrets.PROD_PROJECT_ID}}
      SUPABASE_DB_PASSWORD: ${{secrets.PROD_DB_PASSWORD}}
      SUPABASE_CONNECTION_STRING: ${{secrets.PROD_CONNECTION_STRING}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login into Supabase
        uses: supabase/setup-cli@v1
        with:
          version: 1.86.1

      - name: Deploy Edge Functions
        run: |
          chmod +x ./deploy.sh
          bash ./deploy.sh production
