name: Deploy Functions

on:
  push:
      branches:
        - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.86.1
      - name: Link Supabase Project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Print Environment Variables
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        run: |
          echo "SUPABASE_ACCESS_TOKEN: $SUPABASE_ACCESS_TOKEN"
          echo "SUPABASE_PROJECT_ID: $SUPABASE_PROJECT_ID"
          echo "SUPABASE_DB_PASSWORD: $SUPABASE_DB_PASSWORD"
          echo "SUPABASE_CONNECTION_STRING: $SUPABASE_CONNECTION_STRING"

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh production
